### ISSUE TITLE
Gambler's Chest contains two "Minatures"

### ISSUE THREAD

**Issue by AGN1964** [stdobby/kingdomdeath#7]
Great work on this website!

Your Gambler's Chest tab has a row for 2 Minature, the Cursed Spear and Father & Son.  There is just a typo in the word "Miniature".  This should be merged with the next row, 18 miniature.

Hopefully, this is a data driven table and you do not need to fix any code; just fix the typo in data.

Thanks for doing this!

**Comment by stdobby** [comment]
Thanks for catching that!   I've gone ahead and pushed up the changes along with the stuff for Update #29.
