### ISSUE TITLE
Frogdog and BFGL have different values for the "same" content.

### ISSUE THREAD

**Issue by AGN1964** [stdobby/kingdomdeath#8]
On the pledge value tab, look at the Frogdog pledge (KS value $980) and the Black Friday Gambler's Lantern (KS value $955).  The difference is $25.

The difference is the T-shirt.  The Frogdog shirt has a value of $25, the BFGL has a value of $0.  I think they should both be $25, but I could see you saying they should both be $0.  Whatever, I think they should be the same.

Thanks for all the work!

**Comment by stdobby** [comment]
Gone ahead and made it and the Satan's T-Shirt $25!
