### ISSUE TITLE
Feature Request: Select/Unselect All box for Comparator sections

### ISSUE THREAD

**Issue by NotDomo** [stdobby/kingdomdeath#9]
A "select all"/"unselect all" function would be nice for the "new expansion", "old expansion", and "new pinups" sections in the Comparator.

First time doing anything in github. Apologies if I'm doing anything wrong. =)

**Comment by stdobby** [comment]
Hey!  Yeah I can definitely add that!   I'm actually working on a huge refactor at the moment (new layout, look, etc), so I'll try to get to this as soon as possible.

**Comment by stdobby** [comment]
This should be available now :)
